version: '3'

services:
  webserver:
    build: nginx
    image: webserver
    container_name: Container_NGINX
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - fast-cgi
    restart: unless-stopped
  fast-cgi:
    build: php
    image: fast-cgi
    container_name: Container_WordPress_PHP
    hostname: PHP.incep
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
    restart: unless-stopped
  database:
    build: mariaDB
    image: database
    container_name: Container_DB
    env_file:
      - ./mariaDB/.env
    hostname: DB.incep
    networks:
      - inception_net
    volumes:
      - ./DBdata:/var/lib/mysql/
    restart: unless-stopped

networks:
  inception_net: