version: '3'

services:
#  wordpress:
#    depends_on:
#      - database
#    image: wordpress:latest
#    ports:
#      - "80:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: DB.incep:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: password
#    networks:
#      - inception_net
  webserver:
    build: nginx
    container_name: Container_NGINX
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - fast-cgi
  fast-cgi:
    build: php
    container_name: Container_WordPress_PHP
    hostname: PHP.incep
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
  database:
    build: mariaDB
    container_name: Container_DB
    hostname: DB.incep
    networks:
      - inception_net
    volumes:
      - ./DBdata:/var/lib/mysql/
    

networks:
  inception_net: