version: '3'

services:
  webserver:
    build: nginx
    container_name: Container_NGINX
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - fast-cgi
  fast-cgi:
    build: php
    container_name: Container_WordPress_PHP
    hostname: PHP.incep
    networks:
      - inception_net
    volumes:
      - ./wordpress:/var/www/html/
  database:
    build: mariaDB
    container_name: Container_DB
    hostname: DB.incep
    networks:
      - inception_net
    volumes:
      - ./DBdata:/var/lib/mysql/

networks:
  inception_net: